mavros_node:  # Cambiado de /mavros a mavros_node
  ros__parameters:
    plugin_deny_list:  # Usa el guion bajo para asegurar compatibilidad
      - adsb
      - camera
      - cellular_status
      - companion_process_status
      - distance_sensor
      - fake_gps
      - gimbal_control
      - landing_target
      - log_transfer
      - mag_calibration_status
      - mount_control
      - nav_controller_output
      - obstacle_distance
      - obstacle_distance_3d
      - onboard_computer_status
      - open_drone_id
      - optical_flow
      - play_tune
      - px4flow
      - rallypoint
      - rangefinder
      - terrain
      - tunnel
      - vibration
      - vision_pose_estimate
      - vision_speed_estimate
      - wheel_odometry
      - wind_estimation
