# ============================================================
# MAVROS px4_pluginlists.yaml
# Target  : PX4 v1.12.3 / v1.15 - FMU v2/v5
# ROS     : ROS 2 Jazzy + MAVROS
# FIX     : Namespace apuntando al nodo raiz /mavros
# ============================================================

/mavros:
  ros__parameters:
    plugin_denylist:
      - distance_sensor
      - rangefinder
      - optical_flow
      - image_pub
      - wheel_odometry
      - fake_gps
      - actuator_control
      - rc_io
      - vibration
      - landing_target
      - obstacle_distance
      - terrain
      - wind_estimation
