# ============================================================
# MAVROS px4_config.yaml
# Target  : PX4 v1.12.3 / v1.15 - FMU v2/v5
# ROS     : ROS 2 Jazzy + MAVROS
# FIX     : Cada plugin es un nodo hijo independiente en esta
#           version de MAVROS. El namespace debe ser el nodo
#           completo de cada plugin, no /mavros raiz.
# ============================================================

/mavros:
  ros__parameters:
    startup_px4_usb_quirk: false
    fcu_protocol: "v2.0"

/mavros/local_position:
  ros__parameters:
    frame_id: "odom"
    tf:
      send: true
      frame_id: "odom"
      child_frame_id: "base_link"
      send_fcu: false

/mavros/global_position:
  ros__parameters:
    frame_id: "map"
    child_frame_id: "base_link"
    rot_covariance: 99999.0
    tf:
      send: false
      frame_id: "map"
      child_frame_id: "base_link"

/mavros/imu:
  ros__parameters:
    frame_id: "base_link"
    linear_acceleration_stdev: 0.0003
    angular_velocity_stdev: 0.0003490659
    orientation_stdev: 1.0
    magnetic_stdev: 0.0

/mavros/odometry:
  ros__parameters:
    fcu:
      odom_parent_id_des: "odom"
      odom_child_id_des: "base_link"

/mavros/sys:
  ros__parameters:
    min_voltage: [10.0]
    disable_diag: false

/mavros/time:
  ros__parameters:
    time_ref_source: "fcu"
    timesync_mode: "MAVLINK"
    timesync_avg_alpha: 0.6
